export const ShopActionTypes = {
    FETCH_COLLECTIONS_START: Symbol('SHOP.FETCH_COLLECTIONS_START'),
    FETCH_COLLECTIONS_SUCCESS: Symbol('SHOP.FETCH_COLLECTIONS_SUCCESS'),
    FETCH_COLLECTIONS_FAILURE:  Symbol('SHOP.FETCH_COLLECTIONS_FAILURE')
}